#!/usr/bin/env python3
"""批 1a：新增词条（C1 系 + C2 系）— 直接嵌入 knowledge_base.json"""
import json, sys

KB = 'assets/data/knowledge_base.json'

NEW_TERMS = [
    # ============ C1 系：钱的世界观 ============
    {"term": "活期存款", "aliases": ["活期"], "one_line": "随存随取，利息很低的存款",
     "daily_analogy": "钱包里的零钱：方便，但不会自己变多"},
    {"term": "定期存款", "aliases": ["定期"], "one_line": "约定存期、到期才能取的存款",
     "daily_analogy": "把钱锁进抽屉：存得越久，利息越多"},
    {"term": "利息", "aliases": [], "one_line": "借钱给你的报酬",
     "daily_analogy": "把房子租出去收房租，钱租出去收利息"},
    {"term": "利率", "aliases": [], "one_line": "本金按比例计算的利息水平",
     "daily_analogy": "房租的百分比：房租越贵，房东越开心"},
    {"term": "无风险利率", "aliases": [], "one_line": "几乎不会违约的基准收益率",
     "daily_analogy": "国家信用做担保的存款利息，是衡量一切的尺子"},
    {"term": "本息", "aliases": [], "one_line": "本金加上利息的总和",
     "daily_analogy": "种子加上长出来的粮食，一起收回仓"},
    {"term": "风险等级", "aliases": [], "one_line": "产品按亏损可能性的分级",
     "daily_analogy": "辣椒的辣度分级：不辣到特辣，标好才敢下口"},
    {"term": "理财", "aliases": [], "one_line": "让钱保值增值的安排",
     "daily_analogy": "给家里的钱安排工作：谁管应急、谁管增值"},
    {"term": "投资", "aliases": [], "one_line": "用现在的钱换未来的更多钱",
     "daily_analogy": "种下果树苗，等几年后吃果子"},
    {"term": "投资组合", "aliases": [], "one_line": "多种资产搭配在一起",
     "daily_analogy": "一桌菜不能只有红烧肉，荤素搭配才稳"},
    {"term": "应急金", "aliases": ["备用金"], "one_line": "随时能用的活钱，3-6个月开销",
     "daily_analogy": "家里的灭火器：平时用不上，出事能保命"},
    {"term": "机会成本", "aliases": [], "one_line": "选了A，放弃的B带来的收益",
     "daily_analogy": "钱存了定期，就错过了定投的上涨"},
    {"term": "现金流", "aliases": [], "one_line": "一段时间里进进出出的钱",
     "daily_analogy": "水管里的水：光看存量，还要看流速"},
    {"term": "结余", "aliases": ["余钱"], "one_line": "收入减去支出剩下的钱",
     "daily_analogy": "月底数一数，工资还剩多少"},
    {"term": "储蓄率", "aliases": [], "one_line": "存下来的钱占收入的比例",
     "daily_analogy": "端菜上桌时先给自己留一碗，剩下的才花"},
    {"term": "资产", "aliases": [], "one_line": "能把钱放进你口袋的东西",
     "daily_analogy": "会下蛋的鸡：房子、租金、存款都是鸡"},
    {"term": "负债", "aliases": [], "one_line": "要从你口袋掏钱出去的东西",
     "daily_analogy": "欠了别人的蛋要还，车贷房贷都算"},
    {"term": "净资产", "aliases": [], "one_line": "资产减去负债，真正属于你的钱",
     "daily_analogy": "鸡下的蛋减去欠的蛋，才算你的家底"},
    # ============ C2 系：四大家庭理财工具 ============
    {"term": "资本利得", "aliases": [], "one_line": "低买高卖赚到的差价",
     "daily_analogy": "100块进货的T恤200块卖出，赚的100就是"},
    {"term": "价差", "aliases": [], "one_line": "买入价和卖出价之间的差",
     "daily_analogy": "菜贩的赚头：2块收的菜3块卖"},
    {"term": "供需", "aliases": [], "one_line": "供给和需求决定价格",
     "daily_analogy": "下雨天雨伞就贵：想要的人多了"},
    {"term": "预期", "aliases": [], "one_line": "对未来走势的判断",
     "daily_analogy": "觉得要下雨就提前带伞，大家抢着买伞"},
    {"term": "波动", "aliases": [], "one_line": "价格上上下下的幅度",
     "daily_analogy": "过山车的高低起伏：有波动才有刺激"},
    {"term": "系统性风险", "aliases": [], "one_line": "整个市场一起跌的风险",
     "daily_analogy": "下大雨整条街的摊子一起遭殃"},
    {"term": "非系统性风险", "aliases": [], "one_line": "单个公司特有的风险",
     "daily_analogy": "就你家店门口的树倒了，别家没事"},
    {"term": "退市", "aliases": [], "one_line": "公司被摘牌，不再上市交易",
     "daily_analogy": "店铺倒闭关门，手里的股票可能变废纸"},
    {"term": "每股收益", "aliases": ["EPS"], "one_line": "每股赚到的利润",
     "daily_analogy": "一家店分成100份，每份分到的利润"},
    {"term": "估值", "aliases": [], "one_line": "判断一个东西值多少钱",
     "daily_analogy": "给老房子估价：地段、装修、行情都算"},
    {"term": "散户", "aliases": [], "one_line": "自己拿钱投资的个人",
     "daily_analogy": "菜市场里自己挑菜的散客"},
    {"term": "主动管理", "aliases": [], "one_line": "基金经理自己选股择时",
     "daily_analogy": "大厨自己决定今天做什么菜"},
    {"term": "被动管理", "aliases": [], "one_line": "照着指数复制买入，不做主观判断",
     "daily_analogy": "照菜谱做菜，跟着步骤走"},
    {"term": "票面利率", "aliases": [], "one_line": "债券发行时写明的利息率",
     "daily_analogy": "借条上写好的利息，白纸黑字"},
    {"term": "信用风险", "aliases": [], "one_line": "借钱的人还不上钱的风险",
     "daily_analogy": "把钱借给总赖账的朋友的风险"},
    {"term": "地方债", "aliases": [], "one_line": "地方政府发行的债券",
     "daily_analogy": "县政府打的借条，比私人借条稳"},
    {"term": "公司债", "aliases": [], "one_line": "公司发行的债券",
     "daily_analogy": "公司打的借条，利息高但可能赖账"},
    {"term": "信用评级", "aliases": [], "one_line": "对还钱能力的打分",
     "daily_analogy": "朋友的「靠谱分」：分数高才敢借"},
    {"term": "违约", "aliases": [], "one_line": "到期了却还不上钱",
     "daily_analogy": "朋友说好月底还钱，结果失联了"},
    {"term": "市场利率", "aliases": [], "one_line": "市场上借钱通行要付的价格",
     "daily_analogy": "整个市场的「行情价」：加息就是房租普涨"},
    {"term": "债券价格", "aliases": [], "one_line": "债券在市场上买卖的价格",
     "daily_analogy": "借条的转手价：行情好能卖贵"},
    {"term": "压舱石", "aliases": [], "one_line": "让船稳住的重物，喻稳健资产",
     "daily_analogy": "船底的石头：风浪再大船也不翻"},
    {"term": "股债配置", "aliases": [], "one_line": "股票和债券按比例搭配",
     "daily_analogy": "前锋加后卫：进攻的配防守的"},
    {"term": "相关性", "aliases": [], "one_line": "两个资产同涨同跌的程度",
     "daily_analogy": "双胞胎步调一致程度：A涨B也涨，相关性就高"},
    {"term": "风险承受力", "aliases": [], "one_line": "你能承受多大亏损而不慌",
     "daily_analogy": "能吃多辣的辣度测试：先小口试"},
    {"term": "股票基金", "aliases": [], "one_line": "主要买股票的基金",
     "daily_analogy": "一桌全是荤菜的套餐，口味重、波动大"},
    {"term": "混合基金", "aliases": [], "one_line": "股票债券都买的基金",
     "daily_analogy": "荤素搭配的套餐，营养均衡"},
    {"term": "投资方向", "aliases": [], "one_line": "基金主要把钱投到哪",
     "daily_analogy": "看套餐主打什么菜：是肉是素要先看菜单"},
    {"term": "费率", "aliases": [], "one_line": "买基金要交的各种费用",
     "daily_analogy": "大厨的抽成：别看小，长期是大头"},
    {"term": "未知价原则", "aliases": [], "one_line": "按当天收盘净值成交",
     "daily_analogy": "晚上收市才知道今天的菜价，先点单后算账"},
    {"term": "申购", "aliases": [], "one_line": "买入基金份额",
     "daily_analogy": "进店点单：按今天的价，先付款后上菜"},
    {"term": "赎回", "aliases": [], "one_line": "卖出基金份额",
     "daily_analogy": "结账离店：按今天的价拿回钱"},
    {"term": "申购费", "aliases": [], "one_line": "买入基金时交的手续费",
     "daily_analogy": "点单的服务费，一般1%左右"},
    {"term": "赎回费", "aliases": [], "one_line": "卖出基金时交的手续费",
     "daily_analogy": "退菜的手续费：持有越久越便宜"},
    {"term": "托管费", "aliases": [], "one_line": "银行替你看管资金收的费用",
     "daily_analogy": "存包柜的保管费：钱放银行托管，放心但收费"},
    {"term": "销售服务费", "aliases": [], "one_line": "渠道销售基金收的费用",
     "daily_analogy": "中介带你看房收的费用"},
    {"term": "风格漂移", "aliases": [], "one_line": "基金实际投资偏离宣称的方向",
     "daily_analogy": "招牌写川菜馆，端上来却是粤菜"},
    {"term": "跑赢指数", "aliases": [], "one_line": "收益超过对照基准",
     "daily_analogy": "比整条街平均生意还好"},
    {"term": "风险转移", "aliases": [], "one_line": "把风险转给别人承担",
     "daily_analogy": "自己拿不稳的雷，花钱请别人扛"},
    {"term": "保障型保险", "aliases": [], "one_line": "专门保风险、不带储蓄的保险",
     "daily_analogy": "雨伞：下雨才用，用一次就值"},
    {"term": "理财型保险", "aliases": [], "one_line": "兼有储蓄投资功能的保险",
     "daily_analogy": "带储蓄罐的雨伞：又保又存，但贵"},
    {"term": "年金险", "aliases": [], "one_line": "到约定年龄按年领钱的保险",
     "daily_analogy": "给自己买一份「退休工资」"},
    {"term": "增额终身寿", "aliases": [], "one_line": "保额逐年增长的终身寿险",
     "daily_analogy": "一张会自己长大的存折"},
    {"term": "医保", "aliases": [], "one_line": "国家提供的基础医疗报销",
     "daily_analogy": "国家发的看病补贴：人人有份，先买上"},
    {"term": "百万医疗险", "aliases": [], "one_line": "保额上百万的住院报销医疗险",
     "daily_analogy": "大病报销的巨型雨伞：花小钱挡大浪"},
    {"term": "健康告知", "aliases": [], "one_line": "投保时如实申报身体状况",
     "daily_analogy": "先交体检报告，瞒报可能被拒赔"},
    {"term": "拒赔", "aliases": [], "one_line": "保险公司拒绝赔付",
     "daily_analogy": "伞坏了找厂家，厂家说你自己弄坏的"},
    {"term": "家庭经济支柱", "aliases": [], "one_line": "家里赚钱最多的那个人",
     "daily_analogy": "撑起家的顶梁柱：他最需要保险"},
    {"term": "风险收益", "aliases": [], "one_line": "风险越大，预期收益越高",
     "daily_analogy": "越辣的菜越刺激，但吃多了伤胃"},
]

def main():
    with open(KB, encoding='utf-8') as f:
        kb = json.load(f)
    existing = {g['term'] for g in kb['glossary']}
    added = 0
    for t in NEW_TERMS:
        if t['term'] in existing:
            print(f"SKIP 已存在: {t['term']}")
            continue
        # 字段顺序与现有词条一致
        entry = {"term": t["term"], "aliases": t["aliases"],
                 "one_line": t["one_line"], "daily_analogy": t["daily_analogy"]}
        kb['glossary'].append(entry)
        existing.add(t['term'])
        added += 1
    with open(KB, 'w', encoding='utf-8') as f:
        json.dump(kb, f, ensure_ascii=False, indent=2)
    print(f"✅ 新增 {added} 个词条，词条总数 {len(kb['glossary'])}")

if __name__ == '__main__':
    main()
