#!/usr/bin/env python3
"""批 1b：新增词条（C3 系 + C4 系）"""
import json

KB = 'assets/data/knowledge_base.json'

NEW_TERMS = [
    # ============ C3 系：定投策略 ============
    {"term": "定期定额", "aliases": ["定额定投"], "one_line": "固定时间投固定金额",
     "daily_analogy": "每月定时定量给花浇水，不挑天气"},
    {"term": "择时", "aliases": [], "one_line": "试图猜对买卖的最佳时点",
     "daily_analogy": "天天猜哪天下雨再出门，往往白等"},
    {"term": "筑底", "aliases": [], "one_line": "价格跌到底部横盘整理",
     "daily_analogy": "皮球落地后弹起前，先在地上停一停"},
    {"term": "停扣", "aliases": [], "one_line": "定投中途停止扣款",
     "daily_analogy": "浇水浇到一半停手，苗反而渴死"},
    {"term": "筹码", "aliases": [], "one_line": "手里持有的仓位",
     "daily_analogy": "牌桌上你手里攥着的牌"},
    {"term": "宽基指数", "aliases": [], "one_line": "覆盖多个行业的宽范围指数",
     "daily_analogy": "整座城市的平均物价，不押单一街道"},
    {"term": "定投扣款", "aliases": [], "one_line": "定投约定日自动扣钱买入",
     "daily_analogy": "自动浇花器：到点自己浇水"},
    {"term": "落袋为安", "aliases": [], "one_line": "卖出拿到现金才算真赚",
     "daily_analogy": "菜摘进自家篮子才算收成"},
    {"term": "满仓", "aliases": [], "one_line": "全部资金都买成了资产",
     "daily_analogy": "一顿饭全是硬菜，连口汤都喝不起"},
    {"term": "预期回报", "aliases": [], "one_line": "投资期望获得的收益水平",
     "daily_analogy": "预计这学期能考多少分，不代表一定考到"},
    {"term": "高抛低吸", "aliases": [], "one_line": "高点卖出、低点买入",
     "daily_analogy": "菜贵了卖菜，菜便宜了买菜"},
    {"term": "阈值", "aliases": [], "one_line": "触发行动的那条临界线",
     "daily_analogy": "水烧到100度才开，不到就等"},
    {"term": "纪律", "aliases": [], "one_line": "按计划执行，不靠情绪",
     "daily_analogy": "到点睡觉、到点吃饭，雷打不动"},
    {"term": "长期主义", "aliases": [], "one_line": "用长时间换复利的耐心",
     "daily_analogy": "种树十年后才乘凉，急不得"},
    {"term": "持有期", "aliases": [], "one_line": "从买入到卖出持有的时间",
     "daily_analogy": "菜放冰箱的时间：放得越久越考验品质"},
    {"term": "投机", "aliases": [], "one_line": "短期博弈价格涨跌",
     "daily_analogy": "赌球：刺激，但十赌九输"},
    {"term": "手续费", "aliases": [], "one_line": "交易时交的服务费用",
     "daily_analogy": "过路费：来回都收，频繁走就贵了"},
    {"term": "换手率", "aliases": [], "one_line": "持仓被倒手的速度",
     "daily_analogy": "菜被转手几次：转手越多越不新鲜"},
    {"term": "自动扣款", "aliases": [], "one_line": "到约定日系统自动扣钱",
     "daily_analogy": "水电费自动交：省心不拖欠"},
    {"term": "先储蓄后消费", "aliases": [], "one_line": "发工资先存后花",
     "daily_analogy": "先给储钱罐喂饱，剩下的才上桌"},
    {"term": "年金终值", "aliases": [], "one_line": "定期投入若干年后的总值",
     "daily_analogy": "每月存1000，30年后一共攒下多少"},
    {"term": "月利率", "aliases": [], "one_line": "按月计算的利率",
     "daily_analogy": "按月交的房租换算成比率"},
    {"term": "标普500", "aliases": [], "one_line": "美国500家大公司的指数",
     "daily_analogy": "美国最强500家店的平均生意水平"},
    {"term": "牛熊周期", "aliases": [], "one_line": "涨跌交替的市场大循环",
     "daily_analogy": "四季轮回：冬天总会过去"},
    {"term": "权益类资产", "aliases": [], "one_line": "股票这类股权性质的投资",
     "daily_analogy": "跟店同甘共苦的股份：店赚你赚"},
    {"term": "收益假设", "aliases": [], "one_line": "计算时假定的收益率",
     "daily_analogy": "按亩产800斤算收成，只是假设"},
    {"term": "情绪化交易", "aliases": [], "one_line": "凭心情买卖，不做计划",
     "daily_analogy": "生气了就乱花钱，清醒了后悔"},
    {"term": "行为金融", "aliases": [], "one_line": "研究人的心理如何影响投资",
     "daily_analogy": "研究「为什么人总在同一个坑里摔」"},
    {"term": "自动定投", "aliases": [], "one_line": "设置好后自动执行的定投",
     "daily_analogy": "闹钟到点自动存钱，不靠意志力"},
    {"term": "定投计划", "aliases": [], "one_line": "定投的完整方案：金额/周期/标的",
     "daily_analogy": "给花园写的浇灌日程表"},
    # ============ C4 系：避坑与认知 ============
    {"term": "贪婪", "aliases": [], "one_line": "总想赚更多的心理",
     "daily_analogy": "碗里的还没吃完，就盯着锅里的"},
    {"term": "恐惧", "aliases": [], "one_line": "怕亏钱不敢行动的心理",
     "daily_analogy": "被蛇咬过，看见草绳都绕道"},
    {"term": "行为经济学", "aliases": [], "one_line": "研究人非理性决策的经济学",
     "daily_analogy": "经济学里最接地气的一门：研究人怎么犯傻"},
    {"term": "从众心理", "aliases": [], "one_line": "跟着大多数人做同样的决定",
     "daily_analogy": "看见排队就站过去，先排了再说"},
    {"term": "市场顶部", "aliases": [], "one_line": "行情涨到最高点附近",
     "daily_analogy": "宴席最热闹时，其实快散场了"},
    {"term": "清盘", "aliases": [], "one_line": "基金清算终止运营",
     "daily_analogy": "店铺关门清算，投的钱按净值退回"},
    {"term": "样本", "aliases": [], "one_line": "用来做判断的观察对象",
     "daily_analogy": "尝一口汤就知道整锅咸淡，但锅底没搅匀就错"},
    {"term": "调仓", "aliases": [], "one_line": "调整资产之间的比例",
     "daily_analogy": "换菜换座位：哪个多了撤点，少了补点"},
    {"term": "理性决策", "aliases": [], "one_line": "基于事实和计划做决定",
     "daily_analogy": "看菜谱买菜，而不是看心情下锅"},
    {"term": "成本价", "aliases": [], "one_line": "你买入时的价格",
     "daily_analogy": "进货价：卖不到这个价就亏本"},
    {"term": "回本", "aliases": [], "one_line": "涨回到买入成本",
     "daily_analogy": "把本钱捞回来，一分不多一分不少"},
    {"term": "过度自信", "aliases": [], "one_line": "高估自己的判断能力",
     "daily_analogy": "拿了驾照就觉得自己是赛车手"},
    {"term": "贝塔β", "aliases": ["β"], "one_line": "相对市场整体波动的大小",
     "daily_analogy": "别人晃一下你晃两下：你更敏感"},
    {"term": "阿尔法α", "aliases": ["α"], "one_line": "超越市场平均的超额收益",
     "daily_analogy": "全班平均80分你考90，多的10分"},
    {"term": "投资日志", "aliases": [], "one_line": "记录每次投资决策的日记",
     "daily_analogy": "车上的行车记录仪：事后能复盘"},
    {"term": "牛市末期", "aliases": [], "one_line": "持续上涨接近尾声的阶段",
     "daily_analogy": "烟花最绚烂的那几秒，快没了"},
    {"term": "追高", "aliases": [], "one_line": "涨得高时忍不住买入",
     "daily_analogy": "排长队买最贵的菜，回家才发现贵了"},
    {"term": "接盘", "aliases": [], "one_line": "在高位买入成为最后买单的人",
     "daily_analogy": "烫手山芋转了一圈，最后砸你手里"},
    {"term": "保本高息", "aliases": [], "one_line": "既保本又高息的承诺，基本是骗局",
     "daily_analogy": "又要安全又要暴利，等于要鱼和熊掌"},
    {"term": "资金盘", "aliases": [], "one_line": "用新钱付老钱的游戏",
     "daily_analogy": "拆东墙补西墙，墙塌只差时间"},
    {"term": "带单", "aliases": [], "one_line": "有人带着你买卖",
     "daily_analogy": "有人领着你下注，输了他说跟他没关系"},
    {"term": "野鸡平台", "aliases": [], "one_line": "无牌照不合规的平台",
     "daily_analogy": "路边没执照的流动摊，收钱就跑"},
    {"term": "爆雷", "aliases": [], "one_line": "平台或项目突然崩盘",
     "daily_analogy": "高压锅炸了：之前没一点声响"},
    {"term": "拉人头", "aliases": [], "one_line": "靠发展下线赚钱的模式",
     "daily_analogy": "拉一个人进来给你提成，拉得越多赚越多"},
    {"term": "证监会", "aliases": [], "one_line": "监管证券市场的国家机构",
     "daily_analogy": "证券市场的交警，管秩序查违章"},
    {"term": "金融监管总局", "aliases": [], "one_line": "监管银行保险等金融机构的部门",
     "daily_analogy": "金融界的巡警，管银行保险这条街"},
    {"term": "对公账户", "aliases": [], "one_line": "企业的对公银行账户",
     "daily_analogy": "店铺的公家账本：正规公司都打这"},
    {"term": "黑天鹅", "aliases": [], "one_line": "罕见且影响巨大的事件",
     "daily_analogy": "晴天突然下冰雹，谁都料不到"},
    {"term": "市场情绪", "aliases": [], "one_line": "整个市场的乐观或恐慌程度",
     "daily_analogy": "整条街的喜庆程度：锣鼓喧天时最危险"},
    {"term": "牛市", "aliases": [], "one_line": "市场持续上涨的时期",
     "daily_analogy": "整条街生意红火，人人脸上有光"},
    {"term": "开户数", "aliases": [], "one_line": "新开股票账户的数量",
     "daily_analogy": "新来的顾客数：顾客猛增时菜价常被抬"},
    {"term": "底仓", "aliases": [], "one_line": "长期持有不动的仓位",
     "daily_analogy": "火锅的底料：一直煮一直香"},
    {"term": "熊市", "aliases": [], "one_line": "市场持续下跌的时期",
     "daily_analogy": "整条街生意冷清，关店的关店"},
    {"term": "抄底", "aliases": [], "one_line": "在低点买入",
     "daily_analogy": "趁菜价最便宜时囤货，但可能越囤越跌"},
    {"term": "成交量", "aliases": [], "one_line": "交易的活跃程度",
     "daily_analogy": "菜市场的客流：人多生意旺"},
    {"term": "复盘", "aliases": [], "one_line": "事后回顾总结得失",
     "daily_analogy": "看录像回放，找出自己为什么输"},
    {"term": "决策记录", "aliases": [], "one_line": "记下当时为什么做这个决定",
     "daily_analogy": "记下当时为什么选这家店，事后好对照"},
    {"term": "归零", "aliases": [], "one_line": "本金全部亏光",
     "daily_analogy": "篮子里的菜全烂光，一分不剩"},
    {"term": "认知边界", "aliases": [], "one_line": "自己懂和不懂的界限",
     "daily_analogy": "地图上没画过的地方，别硬闯"},
    {"term": "暴跌", "aliases": [], "one_line": "价格在短时间内大幅下跌",
     "daily_analogy": "菜价一夜腰斩：摊主都在叹气"},
    {"term": "经侦", "aliases": [], "one_line": "专查经济犯罪的警察",
     "daily_analogy": "管骗局的警察：报案就找他"},
    {"term": "96110", "aliases": [], "one_line": "全国统一反诈预警专线",
     "daily_analogy": "反诈热线：接到电话说明你可能正被骗"},
    {"term": "二次诈骗", "aliases": [], "one_line": "被骗后骗子又回来骗一次",
     "daily_analogy": "补刀式骗局：冒充「帮你追回」再骗一次"},
    {"term": "证据保全", "aliases": [], "one_line": "保存好证据防止丢失",
     "daily_analogy": "先拍照留证：转账记录、聊天都留好"},
    {"term": "处置效应", "aliases": [], "one_line": "赚钱就跑、亏钱死扛",
     "daily_analogy": "赚5块就跑，亏50块却死等回本"},
    {"term": "确认偏差", "aliases": [], "one_line": "只看见支持自己想法的信息",
     "daily_analogy": "想买就到处找「要涨」的理由"},
    {"term": "赌徒谬误", "aliases": [], "one_line": "以为独立事件会被过去影响",
     "daily_analogy": "抛硬币连出10次正面，以为下次必是反面"},
    {"term": "框架效应", "aliases": [], "one_line": "同样的事实，说法不同判断就变",
     "daily_analogy": "「存活率90%」和「死亡率10%」其实是同一件事"},
    {"term": "随机性", "aliases": [], "one_line": "无法预测的偶然因素",
     "daily_analogy": "掷骰子：这次6下次还是6都有可能"},
    {"term": "爆仓", "aliases": [], "one_line": "杠杆交易亏光保证金被强平",
     "daily_analogy": "借钱赌身家，输光本金还得倒欠"},
    {"term": "噪音", "aliases": [], "one_line": "无信息含量的干扰信息",
     "daily_analogy": "菜市场的吆喝声：热闹但没有营养"},
    {"term": "信号", "aliases": [], "one_line": "有真实信息含量的数据",
     "daily_analogy": "真正有用的情报，比如财报和成交"},
    {"term": "传销", "aliases": [], "one_line": "靠拉人头发展下线的金字塔模式",
     "daily_analogy": "老鼠会：你的收益全靠新人入场费"},
    {"term": "目标收益率", "aliases": [], "one_line": "预设赚到多少就止盈",
     "daily_analogy": "订好「赚15%就收摊」，到点就撤"},
]

def main():
    with open(KB, encoding='utf-8') as f:
        kb = json.load(f)
    existing = {g['term'] for g in kb['glossary']}
    added = 0
    for t in NEW_TERMS:
        if t['term'] in existing:
            print(f"SKIP 已存在: {t['term']}")
            continue
        kb['glossary'].append({"term": t["term"], "aliases": t["aliases"],
                               "one_line": t["one_line"], "daily_analogy": t["daily_analogy"]})
        existing.add(t['term'])
        added += 1
    with open(KB, 'w', encoding='utf-8') as f:
        json.dump(kb, f, ensure_ascii=False, indent=2)
    print(f"✅ 新增 {added} 个词条，词条总数 {len(kb['glossary'])}")

if __name__ == '__main__':
    main()
